//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZLogisiticsDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HotelInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_HotelInfo()
        {
            this.T_ProductOrder = new HashSet<T_ProductOrder>();
            this.T_HUserInfo = new HashSet<T_HUserInfo>();
        }
    
        public int F_ID { get; set; }
        public string F_Name { get; set; }
        public Nullable<int> F_Level { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductOrder> T_ProductOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_HUserInfo> T_HUserInfo { get; set; }
    }
}
