//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZLogisiticsDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductOrder
    {
        public int F_ID { get; set; }
        public string F_ProductName { get; set; }
        public string F_Model { get; set; }
        public Nullable<int> F_UnitID { get; set; }
        public Nullable<decimal> F_Price { get; set; }
        public string F_Brand { get; set; }
        public Nullable<System.DateTime> F_ImportDate { get; set; }
        public string DeliveryPlace { get; set; }
        public string F_Remark { get; set; }
        public Nullable<int> F_ProviderID { get; set; }
        public Nullable<int> F_HotelID { get; set; }
        public string F_Status { get; set; }
    
        public virtual T_HotelInfo T_HotelInfo { get; set; }
        public virtual T_ProviderInfo T_ProviderInfo { get; set; }
        public virtual T_Unit T_Unit { get; set; }
    }
}
