//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZLogisiticsDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PUserType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PUserType()
        {
            this.T_PUserInfo = new HashSet<T_PUserInfo>();
        }
    
        public int F_ID { get; set; }
        public string F_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PUserInfo> T_PUserInfo { get; set; }
    }
}
