//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZLogisiticsDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PUserInfo
    {
        public int F_ID { get; set; }
        public string F_UserName { get; set; }
        public string F_Password { get; set; }
        public Nullable<int> F_UserTypeID { get; set; }
        public Nullable<int> F_ProviderID { get; set; }
    
        public virtual T_ProviderInfo T_ProviderInfo { get; set; }
        public virtual T_PUserType T_PUserType { get; set; }
    }
}
